name: bump-command
on:
  repository_dispatch:
    types: [bump-command]

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          submodules: recursive

      - uses: expipiplus1/action-automation/bump-version@HEAD
        with:
          token: ${{ secrets.PAT }}
          packageInfos: |
            first:
              directory: .
              tagPrefix: v
            second:
              directory: second
              tagPrefix: other-v
            third:
              directory: third
              tagPrefix: third-v
          packageVersions: |
            ${{ toJson(github.event.client_payload.slash_command.args.named) }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket
