name: bump-command
on:
  repository_dispatch:
    types: [bump-command]

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          submodules: recursive

      - uses: expipiplus1/action-automation/bump-version@HEAD
        with:
          packageInfos: |
            first v .
            second other-v second
            third third-v third
          packageVersions: |
            ${{ toJson(github.event.client_payload.slash_command.args.named) }}

      - run: |
          git push origin HEAD:${{ github.event.client_payload.pull_request.head.ref }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket
