name: Create Release

on:
  push:
    tags:
    - v*
    - other-v*
    - third-v*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build project
      run: |
        ./release.sh \
          --release-note release-note.md \
          --require-first ${{ github.ref }} \
          --assets assets

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        hub release create \
          $(find assets -type f -printf "--attach %p ") \
          --file release-note.md \
          ${{ github.ref }}
