name: Tag Latest Release

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch everything
        token: ${{ secrets.PAT }}
    - uses: expipiplus1/tag-latest-release/tag-latest-release@HEAD
      with:
        token: ${{ secrets.PAT }}
        tagsAndFiles: |
          v package.yaml
          other-v other-package.yaml
          third-v third-package.yaml
