name: Tag Latest Release

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch everything
        token: ${{ secrets.PAT }}
    - run: |
        sudo pip3 install yq
    - run: |
        ./tag-latest-release.sh --package package.yaml --tag-prefix v
        ./tag-latest-release.sh --package other-package.yaml --tag-prefix other-v
        ./tag-latest-release.sh --package third-package.yaml --tag-prefix third-v
        git push --tags
